// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flitclhcgwhtqgbqwzud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsaXRjbGhjZ3dodHFnYnF3enVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyODE1MDEsImV4cCI6MjA1Mzg1NzUwMX0.GZwhjsHZKXxkFrY9CudhGFl2RmQFNv67TYKcrW7cKA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);